Repository uscuni/simplification, pull requests merged in 2024-06, with the labels that each got.

#59 CI & coverage badges on README
  README.md
Labels: housekeeping

#68 update `README.md` for adjusted structure.
  README.md
Labels: housekeeping

#66 further migration of `code` -> `core` [2024-06-12]
  notebooks/_addartifacts_8989.ipynb
  notebooks/_clip_networks.ipynb
  notebooks/_convert.ipynb
  notebooks/cityseer_overview_gaboardi.ipynb
  notebooks/cityseer_parallel_gaboardi.ipynb
  notebooks/clustering.ipynb
  notebooks/evaluate_h3cells.ipynb
  notebooks/momepy.ipynb
  notebooks/osmnx.ipynb
  notebooks/parenx-run.sh
  notebooks/parenx.ipynb
  notebooks/simplification_protocol.ipynb
  notebooks/usecases.ipynb
  notebooks/utils.py
  usecases/1656/cityseer/parallel_edges_1_midline_False.mp4
  usecases/1656/cityseer/parallel_edges_1_midline_True.mp4
  usecases/1656/cityseer/parallel_edges_2_midline_False.mp4
  usecases/1656/cityseer/parallel_edges_2_midline_True.mp4
  usecases/1656/cityseer/parallel_edges_3_midline_False.mp4
  usecases/1656/cityseer/parallel_edges_3_midline_True.mp4
Labels: housekeeping

#69 all `code/utils.py` to `core/*` && `evaluate_h3cells` overhaul
  README.md
  core/__init__.py
  core/stats.py
  core/tests/baseline_images/test_viz_h3_hex/test_viz_h3_hex_plot_analysis.png
  core/tests/baseline_images/test_viz_h3_hex/test_viz_h3_hex_plot_aoi.png
  core/tests/baseline_images/test_viz_h3_hex/test_viz_h3_hex_plot_cell_hex_id.png
  core/tests/baseline_images/test_viz_h3_hex/test_viz_h3_hex_plot_cell_loc_id.png
  core/tests/conftest.py
  core/tests/test_stats.py
  core/tests/test_utils.py
  core/tests/test_viz_context.py
  core/tests/test_viz_h3_hex.py
  core/utils.py
  core/viz/__init__.py
  core/viz/context.py
  core/viz/h3_hex.py
  notebooks/evaluate_h3cells.ipynb
  notebooks/utils.py
  usecases/869/averagedegree/1148.png
  usecases/869/averagedegree/12.png
  usecases/869/averagedegree/1381.png
  usecases/869/averagedegree/1430.png
  usecases/869/averagedegree/28.png
  usecases/869/averagedegree/441.png
  usecases/869/averagedegree/657.png
  usecases/869/averagedegree/83.png
  usecases/869/averagedegree/833.png
  usecases/869/averagedegree/89bb5000413ffff.png
  usecases/869/averagedegree/89bb50006a7ffff.png
  usecases/869/averagedegree/89bb5000b83ffff.png
  usecases/869/averagedegree/89bb50025c3ffff.png
  usecases/869/averagedegree/89bb5002a0bffff.png
  usecases/869/averagedegree/89bb5002c0bffff.png
  usecases/869/averagedegree/89bb50036abffff.png
  usecases/869/averagedegree/89bb5011907ffff.png
  usecases/869/averagedegree/89bb5015697ffff.png
  usecases/869/averagedegree/89bb501ac67ffff.png
  usecases/869/averagedegree/955.png
  usecases/869/totallength/1263.png
  usecases/869/totallength/342.png
  usecases/869/totallength/364.png
  usecases/869/totallength/382.png
  usecases/869/totallength/420.png
  usecases/869/totallength/550.png
  usecases/869/totallength/799.png
  usecases/869/totallength/827.png
  usecases/869/totallength/89bb5000c63ffff.png
  usecases/869/totallength/89bb5002493ffff.png
  usecases/869/totallength/89bb501196fffff.png
  usecases/869/totallength/89bb5011e7bffff.png
  usecases/869/totallength/89bb501a523ffff.png
  usecases/869/totallength/89bb501a833ffff.png
  usecases/869/totallength/89bb501a8a3ffff.png
  usecases/869/totallength/89bb501a8abffff.png
  usecases/869/totallength/89bb501a8b7ffff.png
  usecases/869/totallength/89bb501ad7bffff.png
  usecases/869/totallength/925.png
  usecases/869/totallength/940.png
Labels: housekeeping, DRY

#53 Continuity-preserving simplification of triangular artifacts
  core/__init__.py
  core/algorithms/__init__.py
  core/algorithms/common.py
  core/algorithms/triangles.py
  core/geometry.py
  core/utils.py
  notebooks/triangles.ipynb
Labels: algo/method

#72 Update README.md -- remove `codecov` badge
  README.md
Labels: documentation, housekeeping

#75 test & fix for `geomtry.is_within()`
  core/geometry.py
  core/tests/test_geometry.py
Labels: bug, housekeeping
