Repository uscuni/simplification, pull requests merged in 2024-10, with the labels that each got.

#170 deleted service roads
  ci/py311_simplification-oldest.yaml
  core/tests/baseline_images/test_viz_context/test_viz_context_param_plot_video.png
  core/tests/baseline_images/test_viz_h3_hex/test_viz_h3_hex_plot_aoi.png
  data/8989/manual/8989.parquet
  notebooks/check_corrected_input_data.ipynb
Labels: data

#176 reduce testing matrix - #173
  .github/workflows/testing.yml
  ci/py311_simplification-dev.yaml
  ci/py311_simplification-oldest.yaml
Labels: housekeeping

#178 add `sgeop` as a dep
  ci/py311_simplification-latest.yaml
  environment.yml
  pyproject.toml
Labels: housekeeping, DRY

#180 use token for codecov in testing
  .github/workflows/testing.yml
Labels: housekeeping

#188 Notebooks readme
  README.md
  notebooks/preprocessing/clip_networks.ipynb
  notebooks/preprocessing/remove_degree_2_nodes.ipynb
Labels: documentation
