Repository uscuni/simplification, pull requests merged in 2025-04, with the labels that each got.

#261 adding typology slides
  typology/typology-draft01.key
  typology/typology-draft01.pdf
  typology/typology-draft02.key
  typology/typology-draft02.pdf
Labels: viz

#263 Usecase figs
  core/utils.py
  evaluation-buildings/chi.png
  evaluation-buildings/delta.png
  notebooks/evaluation/statistical_comparison_viz.ipynb
  notebooks/evaluation/statistical_comparison_viz_buildings.ipynb
  notebooks/figures/usecases_paper.ipynb
Labels: cases/results, paper/writing, viz

#270 CES appendix + fix of CES figure
  core/viz/ces.py
  illustrations/ces_liege.pdf
  illustrations/ces_liege.png
  illustrations/ces_liege.svg
  illustrations/ces_liege_ces_only.pdf
  illustrations/ces_liege_ces_only.png
  illustrations/ces_liege_ces_only.svg
  illustrations/ces_liege_post.afdesign
  illustrations/ces_liege_post.pdf
  illustrations/ces_liege_post.png
  illustrations/ces_liege_post_part1.png
  illustrations/ces_liege_post_part2.png
  illustrations/ces_liege_post_part3.png
  illustrations/ces_liege_solution.pdf
  illustrations/ces_liege_solution.png
  illustrations/ces_liege_solution.svg
  illustrations/ces_liege_subset.afdesign
  illustrations/ces_liege_subset.pdf
  illustrations/ces_liege_subset.png
  illustrations/ces_liege_subset.svg
  illustrations/ces_liege_subset_post.pdf
  illustrations/ces_liege_subset_post.png
  notebooks/figures/ces_illustration.ipynb
Labels: paper/writing

#272 update colors of the diagram
  illustrations/Artboard2.png
  illustrations/Artboard3.png
  illustrations/Artboard4.png
  illustrations/Artboard5.png
  illustrations/Artboard6.png
  illustrations/neatnet.drawio
  illustrations/neatnet.png
  illustrations/neatnet.svg
Labels: paper/writing, viz

#276 figure for skeletonization
  illustrations/skeletonize.png
  notebooks/figures/skeletonize_clusters.ipynb
Labels: viz
